DELETE FROM GROUPS WHERE id=999805;
SET BLOBFILE 'C:\Standart-N\exp_to_pharmsm\999805_TMS_EXPORT_TO_PHARMSM.txt';
INSERT INTO GROUPS (ID, PARENT_ID, CAPTION, GROUPTABLE, STATUS, INSERTDT, SYSTEMFLAG, DESCRIPTION, IMAGEINDEX, DATA, COLOR, SORTING, BASE_AGENT_ID, SID) VALUES (999805,-520, 'Выгрузка в PharmSM', 'TMS', 0, NULL, 0, NULL, -1,:h00000000_7FFFFFFF, NULL, NULL, 0, NULL);

commit;







