DELETE FROM GROUPS WHERE id=999803;
DELETE FROM GROUPS WHERE id=999804;
SET BLOBFILE 'e:\TMS\Manager\exp_to_partner\TMS_PARTNER.hex';
INSERT INTO GROUPS (ID, PARENT_ID, CAPTION, GROUPTABLE, STATUS, INSERTDT, SYSTEMFLAG, DESCRIPTION, IMAGEINDEX, DATA, COLOR, SORTING, BASE_AGENT_ID, SID) VALUES (999803, 61, 'Выгрузка в Партнер', 'TMS', 0, NULL, 0, NULL, -1,:h00000000_7FFFFFFF, NULL, NULL, 0, NULL);
SET BLOBFILE 'e:\TMS\Manager\exp_to_partner\TMS_PARTNER_SETUP.hex';
INSERT INTO GROUPS (ID, PARENT_ID, CAPTION, GROUPTABLE, STATUS, INSERTDT, SYSTEMFLAG, DESCRIPTION, IMAGEINDEX, DATA, COLOR, SORTING, BASE_AGENT_ID, SID) VALUES (999804, -400, 'Настройка выгрузки в Партнер', 'TMS', 0, NULL, 0, NULL, -1,:h00000000_7FFFFFFF, NULL, NULL, 0, NULL);

commit;







