
//добавляем новые поля
INSERT INTO ATTRIBUTES (ATTR_SID, ATTR_LINKFIELDNAME, ATTR_TYPE, STATUS, INSERTDT) VALUES ('reg_srok', 'part_id', 3, NULL, null);
INSERT INTO ATTRIBUTES (ATTR_SID, ATTR_LINKFIELDNAME, ATTR_TYPE, STATUS, INSERTDT) VALUES ('reg_date', 'part_id', 3, NULL, null);
INSERT INTO ATTRIBUTES (ATTR_SID, ATTR_LINKFIELDNAME, ATTR_TYPE, STATUS, INSERTDT) VALUES ('reg_who', 'part_id', 0, NULL, null);
INSERT INTO ATTRIBUTES (ATTR_SID, ATTR_LINKFIELDNAME, ATTR_TYPE, STATUS, INSERTDT) VALUES ('poverk_date', 'part_id', 3, NULL, null);
INSERT INTO ATTRIBUTES (ATTR_SID, ATTR_LINKFIELDNAME, ATTR_TYPE, STATUS, INSERTDT) VALUES ('poverk_svid', 'part_id', 0, NULL, null);
INSERT INTO ATTRIBUTES (ATTR_SID, ATTR_LINKFIELDNAME, ATTR_TYPE, STATUS, INSERTDT) VALUES ('poverk_interval', 'part_id', 0, NULL, null);
INSERT INTO ATTRIBUTES (ATTR_SID, ATTR_LINKFIELDNAME, ATTR_TYPE, STATUS, INSERTDT) VALUES ('poverk_nextdate', 'part_id', 03, NULL, null);
INSERT INTO ATTRIBUTES (ATTR_SID, ATTR_LINKFIELDNAME, ATTR_TYPE, STATUS, INSERTDT) VALUES ('reg_udost', 'part_id', 0, NULL, null);
commit work;

//дополняем ввьюху активного документа 
CREATE OR ALTER VIEW VW_DOC_DETAIL_ACTIVE(
    ID,
    PARENT_ID,
    DOC_ID,
    PART_ID,
    PART_PARENT_ID,
    DOC_DETAIL_ID,
    PRICE,
    NAC,
    QUANT,
    DISCOUNT,
    SUMMA,
    SUMMA_O,
    DCARD,
    WARE_ID,
    PRICE_O,
    PRICE_Z,
    PRICE_R,
    BARCODE,
    BARCODE1,
    BCODE_IZG,
    KRITK,
    GODENDO,
    SERIA,
    NDS,
    SUM_NDSO,
    SUM_NDSR,
    SERT,
    DATESERT,
    KEMVSERT,
    SDSERT,
    REGN,
    NGTD,
    EDIZM,
    NAME_ID,
    IZG_ID,
    COUNTRY_ID,
    ORIG_CODE,
    ORIG_NAME_ID,
    ORIG_IZG_ID,
    ORIG_COUNTRY_ID,
    Z_ID,
    SKLAD_ID,
    SNAME,
    SIZG,
    SCOUNTRY,
    SORIG_NAME,
    SORIG_IZG,
    SORIG_COUNTRY,
    INSERTDT,
    INFO,
    KOEF,
    MOTHERPART_ID,
    DEP,
    MMBSH,
    NDSBYDEP,
    REALQUANT,
    PRICE_DSC,
    BLOCK_QUANT,
    SUM_DSC,
    HUMAN_QUANT,
    CUSTOMDRAW,
    STATUS,
    OLDPRICE,
    PART_TYPE,
    PRICES,
    BASE_AGENT_ID,
    SBASE_AGENT_ID,
    GNVLS,
    GROUP_ID,
    MAKE_ID,
    MNN,
    FIO,
    STORE_STRING,
    BARC_LABEL_COUNT,
    SGROUP_ID,
    MGN_NAME,
    MGN_ID,
    MGN_SOURCE,
    OBORUD_INV_NUM,
    OBORUD_ZAV_NUM,
    OBORUD_DATA_IZG,
    reg_udost,
    reg_srok,
    reg_date,
    reg_who,
    poverk_date,
    poverk_svid,
    poverk_interval,
    poverk_nextdate,
    MIN_ZAPAS)
AS
SELECT
da.ID,
PARENT_ID,
DOC_ID,
PART_ID,
PART_PARENT_ID,
DOC_DETAIL_ID,
PRICE,
cast(NAC as numeric(15,2)),
QUANT,
DISCOUNT,
SUMMA,
SUMMA_O,
DCARD,
WARE_ID,
PRICE_O,
PRICE_Z,
PRICE_R,
BARCODE,
BARCODE1,
BCODE_IZG,
(select intvalue from vals where id=da.name_id), --KRITK,
GODENDO,
SERIA,
da.NDS,
SUM_NDSO,
SUM_NDSR,
SERT,
DATESERT,
KEMVSERT,
SDSERT,
REGN,
NGTD,
EDIZM,
NAME_ID,
IZG_ID,
COUNTRY_ID,
ORIG_CODE,
ORIG_NAME_ID,
ORIG_IZG_ID,
ORIG_COUNTRY_ID,
Z_ID,
SKLAD_ID,
SNAME,
SIZG,
SCOUNTRY,
SORIG_NAME,
SORIG_IZG,
SORIG_COUNTRY,
da.INSERTDT,
INFO,
KOEF,
MOTHERPART_ID,
DEP,
(select membership from PR_MEMBERSHIPS('PARTS=' || da.part_id || ';DOC_DETAIL_ACTIVE=' || da.id || ';PARTS.NAME_ID=' || da.name_id || ';PARTS.IZG_ID=' ||da.izg_id ||';',ascii_char(13)||ascii_char(10),1)),
deps.nds,
(select realquant from warebase w where w.part_id=da.part_id),
iif(da.quant between -0.000001 and 0.000001,0,cast(da.summa/da.quant as numeric(15,4))),
(select BLOCK_QUANT from warebase where part_id=da.part_id),
da.SUM_DSC,
da.human_quant,
DA.CUSTOMDRAW,
da.STATUS,
iif(da.parent_id<>0, (select ddd.price from DOC_DETAIL_ACTIVE ddd where ddd.id=da.parent_id),0),
part_type,
(select s from PR_GETPARTPRICES(da.part_id,da.id)),
da.BASE_AGENT_ID,
(select caption from agents where id=da.BASE_AGENT_ID),
da.gnvls,
da.group_id,
da.make_id,
da.mnn,
(select od.fio from DOC_DETAIL_DOCTOR docdoc left join out$traders od on docdoc.doctor_id=od.id where docdoc.doc_detail_active_id =da.id),
(select svalue from pr_getattribute('store_string', da.name_id)),
(select svalue from pr_getattribute('barc_label_count', da.name_id)),
(select gr.caption from groups gr where gr.id=da.group_id),
(select mgn_name from wares where id = da.ware_id) as mgn_name,
(select mgn_id from wares where id = da.ware_id) as mgn_id,
(select mgn_source from wares where id = da.ware_id) as mgn_source,
 (select svalue from pr_getattribute('OBORUD_INV_NUM', da.name_id)),
(select svalue from pr_getattribute('OBORUD_ZAV_NUM', da.name_id)),
(select svalue from pr_getattribute('OBORUD_DATA_IZG', da.name_id)),
(select svalue from pr_getattribute('REG_UDOST', da.part_id)),
(select svalue from pr_getattribute('reg_srok', da.part_id)),
(select svalue from pr_getattribute('reg_date', da.part_id)),
(select svalue from pr_getattribute('reg_who', da.part_id)),
(select svalue from pr_getattribute('poverk_date', da.part_id)),
(select svalue from pr_getattribute('poverk_svid', da.part_id)),
(select svalue from pr_getattribute('poverk_interval', da.part_id)),
(select svalue from pr_getattribute('poverk_nextdate', da.part_id)),
(select svalue from pr_getattribute('MIN_ZAPAS', da.name_id))
FROM
DOC_DETAIL_ACTIVE da left join deps on da.dep=deps.id
order by da.parent_id, da.sname, da.id;
commit work;

//правим вьюху warebase
CREATE OR ALTER VIEW VW_WAREBASE(
    PART_ID,
    WARE_ID,
    SNAME,
    SIZG,
    SCOUNTRY,
    ORIG_CODE,
    SORIG_NAME,
    SORIG_IZG,
    SORIG_COUNTRY,
    BCODE_IZG,
    PRICE,
    PRICE_O,
    PRICE_Z,
    PRICE_R,
    QUANT,
    BARCODE,
    BARCODE1,
    DEP,
    KRITK,
    GODENDO,
    SERIA,
    SUM_NDSO,
    SERT,
    DATESERT,
    KEMVSERT,
    SDSERT,
    REGN,
    NGTD,
    EDIZM,
    DOC_ID,
    DOCNUM,
    DOCDATE,
    DOCCAPTION,
    DOCAGENT,
    DOCVNUM,
    DOCVSHIFT,
    INSERTDT,
    UPDATEDT,
    ENDDT,
    NDS,
    REALQUANT,
    PART_PARENT_ID,
    NAME_ID,
    IZG_ID,
    COUNTRY_ID,
    NAC,
    BLOCK_QUANT,
    BLOCK_COUNT,
    MMBSH,
    PART_TYPE,
    PRICES,
    BASE_AGENT_ID,
    SBASE_AGENT_ID,
    CONTRACT_ID,
    SCONTRACT_ID,
    GROUP_ID,
    SGROUP_ID,
    VPART_ID,
    SKLAD_ID,
    MNN,
    OBORUD_INV_NUM,
    OBORUD_ZAV_NUM,
    OBORUD_DATA_IZG,
    STORE_STRING,
    BARC_LABEL_COUNT,
    MGN_NAME,
    MIN_ZAPAS,
     REG_UDOST,
    REG_SROK,
    REG_DATE,
    REG_WHO,
    POVERK_DATE,
    POVERK_SVID,
    POVERK_INTERVAL,
    POVERK_NEXTDATE,
    SUM_QUANT)
AS
select
PART_ID,
WARE_ID,
SNAME,
SIZG,
SCOUNTRY,
ORIG_CODE,
SORIG_NAME,
SORIG_IZG,
SORIG_COUNTRY,
BCODE_IZG,
PRICE,
PRICE_O,
PRICE_Z,
PRICE_R,
QUANT,
BARCODE,
BARCODE1,
DEP,
(select intvalue from vals where id=name_id), --KRITK,
GODENDO,
SERIA,
SUM_NDSO,
SERT,
DATESERT,
KEMVSERT,
SDSERT,
REGN,
NGTD,
EDIZM,
DOC_ID, /*(select pr.doc_id from pr_getmotherpart(part_id) pr), */
DOCNUM,  /*(select (select ddd.docnum from docs ddd where ddd.id=pr.doc_id) from pr_getmotherpart(part_id) pr),*/
cast (DOCDATE as dm_date), /*(select (select ddd.docdate from docs ddd where ddd.id=pr.doc_id) from pr_getmotherpart(part_id) pr),*/
(select (select ddd.caption from docs ddd where ddd.id=pr.doc_id) from pr_getmotherpart(part_id) pr),
(select (select ddd.sagent from vw_docs ddd where ddd.id=pr.doc_id) from pr_getmotherpart(part_id) pr),
DOCVNUM, /*(select (select ddd.vnum from docs ddd where ddd.id=pr.doc_id) from pr_getmotherpart(part_id) pr),*/
DOCVSHIFT, /*(select (select ddd.vshift from docs ddd where ddd.id=pr.doc_id) from pr_getmotherpart(part_id) pr),*/
INSERTDT,
UPDATEDT,
ENDDT,
NDS,
REALQUANT,
PART_PARENT_ID,
NAME_ID,
IZG_ID,
COUNTRY_ID,
NAC,
BLOCK_QUANT,
BLOCK_COUNT,
(select membership from PR_MEMBERSHIPS('PARTS=' || wb.part_id || ';PARTS.NAME_ID=' || wb.name_id || ';PARTS.IZG_ID=' || wb.izg_id ||';',ascii_char(13)||ascii_char(10),1)),
part_type,
(select s from PR_GETPARTPRICES(wb.part_id,0)),
BASE_AGENT_ID,
(select caption from agents where id=wb.BASE_AGENT_ID),
CONTRACT_ID,
SCONTRACT_ID,
GROUP_ID,
(select gr.caption from groups gr where gr.id=wb.group_id),
VPART_ID,
(select sklad_id from parts where parts.id=wb.part_id),
(select preparedvalue from vals where id=name_id),  --mnn
 (select svalue from pr_getattribute('OBORUD_INV_NUM', wb.name_id)),
(select svalue from pr_getattribute('OBORUD_ZAV_NUM', wb.name_id)),
(select svalue from pr_getattribute('OBORUD_DATA_IZG', wb.name_id)),
(select svalue from pr_getattribute('store_string', wb.name_id)),
(select svalue from pr_getattribute('barc_label_count', wb.name_id)),
(select mgn_name from wares where id = wb.ware_id),
(select svalue from pr_getattribute('MIN_ZAPAS', wb.name_id)),
(select svalue from pr_getattribute('REG_UDOST', wb.part_id)),
(select svalue from pr_getattribute('reg_srok', wb.part_id)),
(select svalue from pr_getattribute('reg_date', wb.part_id)),
(select svalue from pr_getattribute('reg_who', wb.part_id)),
(select svalue from pr_getattribute('poverk_date', wb.part_id)),
(select svalue from pr_getattribute('poverk_svid', wb.part_id)),
(select svalue from pr_getattribute('poverk_interval', wb.part_id)),
(select svalue from pr_getattribute('poverk_nextdate', wb.part_id)),
(select mgn_name from wares where id = wb.ware_id),
(select svalue from pr_getattribute('MIN_ZAPAS', wb.name_id)),
(select sum(quant) from warebase w where w.name_id = wb.name_id)
from WAREBASE wb;
commit work;



