DELETE FROM SP$GROUPS WHERE id=999803;
DELETE FROM SP$GROUPS WHERE id=999804;
SET BLOBFILE 'c:\Standart-N\exp_to_partner\999803.hex';
INSERT INTO SP$GROUPS (ID, PARENT_ID, CAPTION, GROUPTABLE, STATUS, INSERTDT, SYSTEMFLAG, DESCRIPTION, IMAGEINDEX, DATA, COLOR, SORTING, BASE_AGENT_ID, SID) VALUES (999803, 61, 'Выгрузка в Партнер', 'TMS', 0, NULL, 0, NULL, -1,:h00000000_7FFFFFFF, NULL, NULL, 0, NULL);
SET BLOBFILE 'c:\Standart-N\exp_to_partner\999804.hex';
INSERT INTO SP$GROUPS (ID, PARENT_ID, CAPTION, GROUPTABLE, STATUS, INSERTDT, SYSTEMFLAG, DESCRIPTION, IMAGEINDEX, DATA, COLOR, SORTING, BASE_AGENT_ID, SID) VALUES (999804, -400, 'Настройка выгрузки в Партнер', 'TMS', 0, NULL, 0, NULL, -1,:h00000000_7FFFFFFF, NULL, NULL, 0, NULL);

commit;







