/******************************************************************************/
/***               Generated by IBExpert 14.05.2019 17:12:52                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_PARTNER_LOAD_ID;

CREATE TABLE PARTNER_LOAD (
    ID              DM_ID /* DM_ID = BIGINT NOT NULL */,
    SNAME           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PART_ID         DM_ID /* DM_ID = BIGINT NOT NULL */,
    DOCNUM          DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DOCDATE         DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DOCAGENT        DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    IZG_ID          DM_UUID_NULL /* DM_UUID_NULL = CHAR(36) */,
    SIZG            DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    SCOUNTRY        DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    BARCODE         DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PRICE_O         DM_DOUBLE /* DM_DOUBLE = DOUBLE PRECISION */,
    PRICE           DM_DOUBLE /* DM_DOUBLE = DOUBLE PRECISION */,
    GODENDO_DATE    DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    SERIA           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    QUANT           DM_DOUBLE /* DM_DOUBLE = DOUBLE PRECISION */,
    INN             DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    BCODE_IZG       DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DOC_COMMITDATE  DM_DATETIME /* DM_DATETIME = TIMESTAMP */,
    INSERTDT        DM_DATETIME /* DM_DATETIME = TIMESTAMP */,
    Q_DATE          DM_DATETIME /* DM_DATETIME = TIMESTAMP */,
    G$PROFILE_ID    DM_ID_NULL /* DM_ID_NULL = BIGINT */,
    PARTNER_ID      DM_ID_NULL /* DM_ID_NULL = BIGINT */
);




/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX PARTNER_LOAD_IDX1 ON PARTNER_LOAD (ID);
CREATE INDEX PARTNER_LOAD_IDX2 ON PARTNER_LOAD (PART_ID);
CREATE INDEX PARTNER_LOAD_IDX3 ON PARTNER_LOAD (QUANT);
CREATE INDEX PARTNER_LOAD_IDX4 ON PARTNER_LOAD (G$PROFILE_ID);
CREATE INDEX PARTNER_LOAD_IDX5 ON PARTNER_LOAD (PARTNER_ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: PARTNER_LOAD_BI */
CREATE OR ALTER TRIGGER PARTNER_LOAD_BI FOR PARTNER_LOAD
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_partner_load_id,1);
end
^


/* Trigger: PARTNER_LOAD_BI0 */
CREATE OR ALTER TRIGGER PARTNER_LOAD_BI0 FOR PARTNER_LOAD
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
begin
  new.insertdt=current_timestamp;
  new.partner_id = (select g.partner_id from g$profiles g where g.id=new.g$profile_id);
end
^

SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
