/******************************************************************************/
/***               Generated by IBExpert 14.05.2019 17:13:09                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_PARTNER_LOAD_BEGIN_ID;

CREATE TABLE PARTNER_LOAD_BEGIN (
    ID            DM_ID /* DM_ID = BIGINT NOT NULL */,
    PART_ID       DM_ID /* DM_ID = BIGINT NOT NULL */,
    QUANT         DM_DOUBLE /* DM_DOUBLE = DOUBLE PRECISION */,
    Q_DATE        DM_DATETIME /* DM_DATETIME = TIMESTAMP */,
    G$PROFILE_ID  DM_ID_NULL /* DM_ID_NULL = BIGINT */
);




/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX PARTNER_LOAD_BEGIN_IDX1 ON PARTNER_LOAD_BEGIN (PART_ID);
CREATE INDEX PARTNER_LOAD_BEGIN_IDX2 ON PARTNER_LOAD_BEGIN (QUANT);
CREATE INDEX PARTNER_LOAD_BEGIN_IDX3 ON PARTNER_LOAD_BEGIN (G$PROFILE_ID);
CREATE INDEX PARTNER_LOAD_BEGIN_IDX4 ON PARTNER_LOAD_BEGIN (Q_DATE);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: PARTNER_LOAD_BEGIN_BI */
CREATE OR ALTER TRIGGER PARTNER_LOAD_BEGIN_BI FOR PARTNER_LOAD_BEGIN
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_partner_load_begin_id,1);
end
^

SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
