/******************************************************************************/
/***               Generated by IBExpert 20.09.2019 10:08:33                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE PHARMIT_OUT (
    TYPE_ID         DM_ID_NULL /* DM_ID_NULL = BIGINT */,
    SALEDATE        DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    EXTERNALGOODID  DM_UUID_NULL /* DM_UUID_NULL = CHAR(36) */,
    GOODNAME        DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PRODUCERNAME    DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    QUANTITY        DM_NUMERIC /* DM_NUMERIC = NUMERIC(15,2) */,
    WHOLESALEPRICE  DM_ID_NULL /* DM_ID_NULL = BIGINT */,
    PRICE           DM_ID_NULL /* DM_ID_NULL = BIGINT */,
    PROVIDERID      DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PHARM           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PHARMBIN        DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PHARMADDRESS    DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    POSTINDEX       DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    LOCATION        DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    USERID          DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    EXTERNALID      DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    TENDER          DM_ID_NULL /* DM_ID_NULL = BIGINT */,
    COORDINATES     DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    INSERTDT        DM_DATETIME /* DM_DATETIME = TIMESTAMP */,
    SENDDT          DM_DATETIME /* DM_DATETIME = TIMESTAMP */,
    POST            DM_TEXT_BIG /* DM_TEXT_BIG = VARCHAR(10000) */,
    ANSWER          DM_TEXT_BIG /* DM_TEXT_BIG = VARCHAR(10000) */,
    UUID            DM_UUID_NULL /* DM_UUID_NULL = CHAR(36) */
);




/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX PHARMIT_OUT_IDX1 ON PHARMIT_OUT (EXTERNALGOODID);
CREATE INDEX PHARMIT_OUT_IDX2 ON PHARMIT_OUT (SALEDATE);
CREATE UNIQUE INDEX PHARMIT_OUT_IDX3 ON PHARMIT_OUT (UUID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: PHARMIT_OUT_BI0 */
CREATE OR ALTER TRIGGER PHARMIT_OUT_BI0 FOR PHARMIT_OUT
ACTIVE BEFORE INSERT POSITION 0
AS
begin

  new.insertdt = current_timestamp;
end
^


/* Trigger: PHARMIT_OUT_BI1 */
CREATE OR ALTER TRIGGER PHARMIT_OUT_BI1 FOR PHARMIT_OUT
ACTIVE BEFORE INSERT OR UPDATE POSITION 1
AS
begin
if (new.type_id =6) then new.quantity = -new.quantity;

end
^


/* Trigger: PHARMIT_OUT_BI_UUID */
CREATE OR ALTER TRIGGER PHARMIT_OUT_BI_UUID FOR PHARMIT_OUT
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
begin
   if (new.uuid is null) then new.uuid=UUID_TO_CHAR(GEN_UUID());
end
^


/* Trigger: PHARMIT_OUT_TENDER */
CREATE OR ALTER TRIGGER PHARMIT_OUT_TENDER FOR PHARMIT_OUT
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
begin
  new.tender =0;
end
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
