/******************************************************************************/
/***               Generated by IBExpert 26.08.2021 15:12:12                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE PHARMIT_OUT_DECADE (
    TYPEID        DM_ID_NULL /* DM_ID_NULL = BIGINT */,
    TENDER        DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    GOODNAME      DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PRODUCERNAME  DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PHARM         DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PHARMADDRESS  DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    BARCODE       DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    QUANTITY      DM_DOUBLE /* DM_DOUBLE = DOUBLE PRECISION */,
    PROFILE_ID    DM_ID /* DM_ID = BIGINT NOT NULL */
);




/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
