/******************************************************************************/
/***               Generated by IBExpert 15.04.2019 14:32:18                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_ANALYTIC_VED_PARAMS_ID;

CREATE TABLE ANALYTIC_VED_PARAMS (
    ID              DM_ID NOT NULL /* DM_ID = BIGINT NOT NULL */,
    ANALITIC_UUID   DM_UUID /* DM_UUID = CHAR(36) NOT NULL */,
    PERIOD_BEG      DM_DATE /* DM_DATE = DATE */,
    PERIOD_END      DM_DATE /* DM_DATE = DATE */,
    WARES_SET_UUID  DM_TEXT1024 /* DM_TEXT1024 = VARCHAR(1024) */,
    G$PROFILE_ID    DM_TEXT1024 /* DM_TEXT1024 = VARCHAR(1024) */,
    USER_ID         DM_ID_NULL /* DM_ID_NULL = BIGINT */
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE ANALYTIC_VED_PARAMS ADD CONSTRAINT PK_ANALYTIC_VED_PARAMS PRIMARY KEY (ID);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX ANALYTIC_VED_PARAMS_IDX1 ON ANALYTIC_VED_PARAMS (ANALITIC_UUID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: ANALYTIC_VED_PARAMS_BI */
CREATE OR ALTER TRIGGER ANALYTIC_VED_PARAMS_BI FOR ANALYTIC_VED_PARAMS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_analytic_VED_params_id,1);
end
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
