
Create_ASNA_GOODS_TABLE=("CREATE TABLE ASNA_GOODS ("\
    "ID        DM_UUID /* DM_UUID = CHAR(36) NOT NULL */,"\
    "MGN_NAME  DM_TEXT1024 NOT NULL /* DM_TEXT1024 = VARCHAR(1024) */,"\
    "PRODUCER  DM_TEXT /* DM_TEXT = VARCHAR(250) */,"\
    "COUNTRY   DM_TEXT /* DM_TEXT = VARCHAR(250) */,"\
    "EAN       DM_TEXT /* DM_TEXT = VARCHAR(250) */,"\
    "INSERTDT  DM_DATETIME /* DM_DATETIME = TIMESTAMP */,"\
    "ACTUAL    DM_ID_NULL /* DM_ID_NULL = BIGINT */)",
    "ALTER TABLE ASNA_GOODS ADD CONSTRAINT UNQ1_ASNA_GOODS UNIQUE (MGN_NAME, PRODUCER, EAN, COUNTRY)",
    "ALTER TABLE ASNA_GOODS ADD CONSTRAINT PK_ASNA_GOODS PRIMARY KEY (ID)",
    "CREATE INDEX ASNA_GOODS_IDX1 ON ASNA_GOODS (EAN)",
    "CREATE INDEX ASNA_GOODS_IDX2 ON ASNA_GOODS (INSERTDT)",
    "CREATE INDEX ASNA_GOODS_IDX3 ON ASNA_GOODS (PRODUCER)",
    "CREATE INDEX ASNA_GOODS_IDX4 ON ASNA_GOODS (ACTUAL)",
    "CREATE OR ALTER TRIGGER ASNA_GOODS_BI0 FOR ASNA_GOODS "\
    "ACTIVE BEFORE INSERT POSITION 0"\
    "AS\n "\
    "begin\n"\
    "  if (new.id is null) then\n"\
    "   new.id = UUID_TO_CHAR(GEN_UUID());\n"\
    "  new.insertdt = CURRENT_TIMESTAMP;\n"\
    "  new.actual = 1;\n"\
    " end ",
    # "^"\
    "CREATE OR ALTER TRIGGER ASNA_GOODS_BU0 FOR ASNA_GOODS "\
    "ACTIVE BEFORE UPDATE POSITION 0"\
    "AS \n"\
    "begin\n"\
    "  if (new.ean is null) then new.ean = '';\n"\
    "end \n")
