/******************************************************************************/
/***                Generated by IBExpert 09.04.2019 8:47:51                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_SOZVEZDIE_ACTION_BATCH_ID;

CREATE TABLE SOZVEZDIE_ACTION_BATCH (
    ID              DM_ID /* DM_ID = BIGINT */,
    MAP_BATCH_ID    DM_ID /* DM_ID = BIGINT */,
    REAL_QUANT_BEG  DM_DOUBLE /* DM_DOUBLE = DOUBLE PRECISION */
);




/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX SOZVEZDIE_ACTION_BATCH_ID ON SOZVEZDIE_ACTION_BATCH (MAP_BATCH_ID);
CREATE UNIQUE INDEX SOZVEZDIE_ACTION_BATCH_IDX1 ON SOZVEZDIE_ACTION_BATCH (ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: SOZVEZDIE_ACTION_BATCH_BI */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_BATCH_BI FOR SOZVEZDIE_ACTION_BATCH
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_sozvezdie_action_batch_id,1);
end
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
