/******************************************************************************/
/***                Generated by IBExpert 09.04.2019 8:46:09                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_SOZVEZDIE_ACTION_MOVE_ID;

CREATE TABLE SOZVEZDIE_ACTION_MOVE (
    ID                   INTEGER,
    MAP_PHARMACY_ID      DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DISTRIBUTION_ID      DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    BATCH_ID             DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DOC_DATE             DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DOC_TYPE             DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DOC_NUMBER           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    POS_NUMBER           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    CHECK_NUMBER         DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    CHECK_UNIQUE_NUMBER  DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    QUANTITY             DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PURCHASE_SUM_NDS     DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    RETAIL_SUM_NDS       DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DISCOUNT_SUM         DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    CASHIER_ID           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    CASHIER_FULL_NAME    DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    CASHIER_TIN          DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    RESALE_SIGN          DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    XML                  DM_TEXT_BIG /* DM_TEXT_BIG = VARCHAR(10000) */,
    FIRSTTIME            DM_ID /* DM_ID = BIGINT */
);




/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE UNIQUE INDEX SOZVEZDIE_ACTION_MOVE_IDX1 ON SOZVEZDIE_ACTION_MOVE (ID);
CREATE UNIQUE INDEX SOZVEZDIE_ACTION_MOVE_IDX2 ON SOZVEZDIE_ACTION_MOVE (DISTRIBUTION_ID, ID, BATCH_ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: SOZVEZDIE_ACTION_MOVE_BI */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_MOVE_BI FOR SOZVEZDIE_ACTION_MOVE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_sozvezdie_action_move_id,1);
end
^


/* Trigger: SOZVEZDIE_ACTION_MOVE_BI0 */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_MOVE_BI0 FOR SOZVEZDIE_ACTION_MOVE
ACTIVE BEFORE INSERT OR UPDATE POSITION 1
AS
begin
    new.xml='<distribution>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
    new.xml=new.xml||'<map_pharmacy_id>'||new.map_pharmacy_id||'</map_pharmacy_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<distribution_id>'||new.distribution_id||'</distribution_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<batch_id>'||new.batch_id||'</batch_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<doc_date>'||new.doc_date||'</doc_date>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<doc_type>'||new.doc_type||'</doc_type>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<doc_number>'||new.doc_number||'</doc_number>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<pos_number>'||new.pos_number||'</pos_number>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<check_number>'||new.check_number||'</check_number>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<check_unique_number>'||new.check_unique_number||'</check_unique_number>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
    new.xml=new.xml||'<quantity>'||new.quantity||'</quantity>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<purchase_sum_nds>'||new.purchase_sum_nds||'</purchase_sum_nds>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<retail_sum_nds>'||new.retail_sum_nds||'</retail_sum_nds>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<discount_sum>'||new.discount_sum||'</discount_sum>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<cashier_id>'||new.cashier_id||'</cashier_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<cashier_full_name>'||new.cashier_full_name||'</cashier_full_name>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<cashier_tin>'||new.cashier_tin||'</cashier_tin>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<resale_sign>'||new.resale_sign||'</resale_sign>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'</distribution>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;

end
^


/* Trigger: SOZVEZDIE_ACTION_MOVE_BI1 */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_MOVE_BI1 FOR SOZVEZDIE_ACTION_MOVE
ACTIVE BEFORE INSERT POSITION 0
AS

begin

 new.doc_number=replace(new.doc_number,'&','&amp;');
 new.doc_number=replace(new.doc_number,'<','&lt;');
 new.doc_number=replace(new.doc_number,'>','&gt;');
 new.doc_number=replace(new.doc_number,'''','&apos;');
 new.doc_number=replace(new.doc_number,'"','&quot;');

 new.cashier_full_name=replace(new.cashier_full_name,'&','&amp;');
 new.cashier_full_name=replace(new.cashier_full_name,'<','&lt;');
 new.cashier_full_name=replace(new.cashier_full_name,'>','&gt;');
 new.cashier_full_name=replace(new.cashier_full_name,'''','&apos;');
 new.cashier_full_name=replace(new.cashier_full_name,'"','&quot;');



end
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
