/******************************************************************************/
/***                Generated by IBExpert 09.04.2019 8:44:25                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_SOZVEZDIE_ACTION_REMHANT_ID;

CREATE TABLE SOZVEZDIE_ACTION_REMHANT (
    ID                               DM_ID /* DM_ID = BIGINT */,
    MAP_PHARMACY_ID                  DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    BATCH_ID                         DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DATES                            DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    OPENING_BALANCE                  DM_DOUBLE /* DM_DOUBLE = DOUBLE PRECISION */,
    CLOSING_BALANCE                  DM_DOUBLE /* DM_DOUBLE = DOUBLE PRECISION */,
    INPUT_RETAIL_PRICE_BALANCE       NUMERIC(15,2),
    INPUT_PURCHASING_PRICE_BALANCE   NUMERIC(15,2),
    OUTPUT_RETAIL_PRICE_BALANCE      NUMERIC(15,2),
    OUTPUT_PURCHASING_PRICE_BALANCE  NUMERIC(15,2),
    PRICE                            DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PRICE_O                          DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    XML                              DM_TEXT_BIG /* DM_TEXT_BIG = VARCHAR(10000) */
);




/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: SOZVEZDIE_ACTION_REMHANT_BI */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_REMHANT_BI FOR SOZVEZDIE_ACTION_REMHANT
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_SOZVEZDIE_ACTION_REMHANT_id,1);
end
^


/* Trigger: SOZVEZDIE_ACTION_REMHANT_BIU0 */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_REMHANT_BIU0 FOR SOZVEZDIE_ACTION_REMHANT
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
begin
  new.xml='<remnant>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
   new.xml=new.xml||'<map_pharmacy_id>'||new.map_pharmacy_id||'</map_pharmacy_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<batch_id>'||new.batch_id||'</batch_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<date>'||new.dates||'</date>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<opening_balance>'||round(new.opening_balance,6)||'</opening_balance>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<closing_balance>'||round(new.closing_balance,6)||'</closing_balance>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<input_retail_price_balance>'||new.input_retail_price_balance||'</input_retail_price_balance>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<input_purchasing_price_balance>'||new.input_purchasing_price_balance||'</input_purchasing_price_balance>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<output_retail_price_balance>'||new.output_retail_price_balance||'</output_retail_price_balance>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<output_purchasing_price_balance>'||new.output_purchasing_price_balance||'</output_purchasing_price_balance>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'</remnant>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;

end
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
