
/******************************************************************************/
/***               Generated by IBExpert 05.04.2019 15:59:50                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3; 


SET TERM ^ ;

create or alter procedure EXTRACT_DIGITS (
    STRING varchar(32))
returns (
    DIGITS varchar(32))
as
declare variable CH char(1);
declare variable L integer;
declare variable I integer;
begin
   digits = '';
   L = CHAR_LENGTH(string);
   I = 1;
   while (I <= L) do begin
      CH = substring(STRING from I for 1);
      if (CH between '0' and '9') then
         DIGITS = DIGITS || CH;
      I = I + 1;
   end
  suspend;
end^

SET TERM ; ^

/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_SOZVEZDIE_ACTION_BATCH_ID;

CREATE TABLE SOZVEZDIE_ACTION_BATCH (
    ID              DM_ID /* DM_ID = BIGINT */,
    MAP_BATCH_ID    DM_ID /* DM_ID = BIGINT */,
    REAL_QUANT_BEG  DM_DOUBLE /* DM_DOUBLE = DOUBLE PRECISION */
);




/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX SOZVEZDIE_ACTION_BATCH_ID ON SOZVEZDIE_ACTION_BATCH (MAP_BATCH_ID);
CREATE UNIQUE INDEX SOZVEZDIE_ACTION_BATCH_IDX1 ON SOZVEZDIE_ACTION_BATCH (ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: SOZVEZDIE_ACTION_BATCH_BI */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_BATCH_BI FOR SOZVEZDIE_ACTION_BATCH
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_sozvezdie_action_batch_id,1);
end
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
/******************************************************************************/
/***               Generated by IBExpert 05.04.2019 16:08:05                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_SOZVEZDIE_ACTION_BATCH1_ID;

CREATE TABLE SOZVEZDIE_ACTION_BATCH1 (
    ID                         DM_ID /* DM_ID = BIGINT */,
    MAP_BATCH_ID               DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    MAP_PHARMACY_NAME          DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    NOMENCLATURE_ID            DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    MAP_NOMENCLATURE_NAME      DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    MAP_PRODUCT_CODE           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    MAP_PRODUCT_NAME           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PRODUCER_ID                DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    MAP_PRODUCER_CODE          DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    MAP_PRODUCER_NAME          DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PRODUCER_COUNTRY_ID        DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    MAP_PRODUCER_COUNTRY_CODE  DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    MAP_PRODUCER_COUNTRY_NAME  DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    MAP_SUPPLIER_CODE          DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    MAP_SUPPLIER_TIN           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    SUPPLIER_NAME              DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    BATCH_DOC_DATE             DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    BATCH_DOC_NUMBER           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PURCHASE_PRICE_NDS         DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PURCHASE_NDS               DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    RETAIL_PRICE_NDS           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    BARCODE                    DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    SIGN_COMISSION             DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    NOMENCLATURE_CODES         DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    REAL_QUANT_BEG             DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    MAP_PHARMACY_ID            DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    RETAIL_NDS                 DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    XML                        DM_TEXT_BIG /* DM_TEXT_BIG = VARCHAR(10000) */
);




/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX SOZVEZDIE_ACTION_BATCH1_ID ON SOZVEZDIE_ACTION_BATCH1 (MAP_BATCH_ID);
CREATE UNIQUE INDEX SOZVEZDIE_ACTION_BATCH1_IDX1 ON SOZVEZDIE_ACTION_BATCH1 (ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: SOZVEZDIE_ACTION_BATCH1_BI */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_BATCH1_BI FOR SOZVEZDIE_ACTION_BATCH1
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_SOZVEZDIE_ACTION_BATCH1_id,1);
end
^


/* Trigger: SOZVEZDIE_ACTION_BATCH1_BI1 */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_BATCH1_BI1 FOR SOZVEZDIE_ACTION_BATCH1
ACTIVE BEFORE INSERT POSITION 0
AS
begin
 new.map_pharmacy_name=replace(new.map_pharmacy_name,'&','&amp;');
 new.map_pharmacy_name=replace(new.map_pharmacy_name,'<','&lt;');
 new.map_pharmacy_name=replace(new.map_pharmacy_name,'>','&gt;');
 new.map_pharmacy_name=replace(new.map_pharmacy_name,'''','&apos;');
 new.map_pharmacy_name=replace(new.map_pharmacy_name,'"','&quot;');

 new.map_nomenclature_name=replace(new.map_nomenclature_name,'&','&amp;');
 new.map_nomenclature_name=replace(new.map_nomenclature_name,'<','&lt;');
 new.map_nomenclature_name=replace(new.map_nomenclature_name,'>','&gt;');
 new.map_nomenclature_name=replace(new.map_nomenclature_name,'''','&apos;');
 new.map_nomenclature_name=replace(new.map_nomenclature_name,'"','&quot;');

  new.map_product_name=replace(new.map_product_name,'&','&amp;');
 new.map_product_name=replace(new.map_product_name,'<','&lt;');
 new.map_product_name=replace(new.map_product_name,'>','&gt;');
 new.map_product_name=replace(new.map_product_name,'''','&apos;');
 new.map_product_name=replace(new.map_product_name,'"','&quot;');

 new.map_producer_name=replace(new.map_producer_name,'&','&amp;');
 new.map_producer_name=replace(new.map_producer_name,'<','&lt;');
 new.map_producer_name=replace(new.map_producer_name,'>','&gt;');
 new.map_producer_name=replace(new.map_producer_name,'''','&apos;');
 new.map_producer_name=replace(new.map_producer_name,'"','&quot;');

 new.map_producer_country_name=replace(new.map_producer_country_name,'&','&amp;');
 new.map_producer_country_name=replace(new.map_producer_country_name,'<','&lt;');
 new.map_producer_country_name=replace(new.map_producer_country_name,'>','&gt;');
 new.map_producer_country_name=replace(new.map_producer_country_name,'''','&apos;');
 new.map_producer_country_name=replace(new.map_producer_country_name,'"','&quot;');

 new.supplier_name=replace(new.supplier_name,'&','&amp;');
 new.supplier_name=replace(new.supplier_name,'<','&lt;');
 new.supplier_name=replace(new.supplier_name,'>','&gt;');
 new.supplier_name=replace(new.supplier_name,'''','&apos;');
 new.supplier_name=replace(new.supplier_name,'"','&quot;');
 
 new.batch_doc_number=replace(new.batch_doc_number,'&','&amp;');
 new.batch_doc_number=replace(new.batch_doc_number,'<','&lt;');
 new.batch_doc_number=replace(new.batch_doc_number,'>','&gt;');
 new.batch_doc_number=replace(new.batch_doc_number,'''','&apos;');
 new.batch_doc_number=replace(new.batch_doc_number,'"','&quot;');

 select digits from extract_digits(new.barcode) into new.barcode;
end
^


/* Trigger: SOZVEZDIE_ACTION_BATCH1_BIU0 */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_BATCH1_BIU0 FOR SOZVEZDIE_ACTION_BATCH1
ACTIVE BEFORE INSERT OR UPDATE POSITION 1
AS
begin
  new.xml='<batch>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<map_batch_id>'||new.map_batch_id||'</map_batch_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<map_pharmacy_id>'||new.map_pharmacy_id||'</map_pharmacy_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<map_pharmacy_name>'||new.MAP_PHARMACY_NAME||'</map_pharmacy_name>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<nomenclature_id>'||new.nomenclature_id||'</nomenclature_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<map_nomenclature_name>'||new.map_nomenclature_name||'</map_nomenclature_name>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<map_product_code>'||new.map_product_code||'</map_product_code>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<map_product_name>'||new.map_product_name||'</map_product_name>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<producer_id>'||new.producer_id||'</producer_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<map_producer_code>'||new.map_producer_code||'</map_producer_code>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<map_producer_name>'||new.map_producer_name||'</map_producer_name>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<producer_country_id>'||new.producer_country_id||'</producer_country_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<map_producer_country_code>'||new.map_producer_country_code||'</map_producer_country_code>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
   new.xml=new.xml||'<map_producer_country_name>'||new.map_producer_country_name||'</map_producer_country_name>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<map_supplier_code>'||new.map_supplier_code||'</map_supplier_code>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<map_supplier_tin>'||coalesce(new.map_supplier_tin, '')||'</map_supplier_tin>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<supplier_name>'||new.supplier_name||'</supplier_name>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<batch_doc_date>'||new.batch_doc_date||'</batch_doc_date>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
    new.xml=new.xml||'<batch_doc_number>'||new.batch_doc_number||'</batch_doc_number>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<purchase_price_nds>'||new.purchase_price_nds||'</purchase_price_nds>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
   new.xml=new.xml||'<purchase_nds>'||new.purchase_nds||'</purchase_nds>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<retail_price_nds>'||new.retail_price_nds||'</retail_price_nds>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<retail_nds>'||new.retail_nds||'</retail_nds>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<barcode>'||trim(new.barcode)||'</barcode>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<sign_comission>'||new.sign_comission||'</sign_comission>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
   new.xml=new.xml||'<nomenclature_codes>'||'<code owner="map">'||new.nomenclature_codes||'</code>'||'</nomenclature_codes>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'</batch>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;

end
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
/******************************************************************************/
/***               Generated by IBExpert 05.04.2019 16:08:22                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_SOZVEZDIE_ACTION_MOVE_ID;

CREATE TABLE SOZVEZDIE_ACTION_MOVE (
    ID                   INTEGER,
    MAP_PHARMACY_ID      DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DISTRIBUTION_ID      DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    BATCH_ID             DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DOC_DATE             DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DOC_TYPE             DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DOC_NUMBER           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    POS_NUMBER           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    CHECK_NUMBER         DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    CHECK_UNIQUE_NUMBER  DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    QUANTITY             DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PURCHASE_SUM_NDS     DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    RETAIL_SUM_NDS       DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DISCOUNT_SUM         DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    CASHIER_ID           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    CASHIER_FULL_NAME    DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    CASHIER_TIN          DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    RESALE_SIGN          DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    XML                  DM_TEXT_BIG /* DM_TEXT_BIG = VARCHAR(10000) */,
    FIRSTTIME            DM_ID /* DM_ID = BIGINT */
);




/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: SOZVEZDIE_ACTION_MOVE_BI */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_MOVE_BI FOR SOZVEZDIE_ACTION_MOVE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_sozvezdie_action_move_id,1);
end
^


/* Trigger: SOZVEZDIE_ACTION_MOVE_BI0 */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_MOVE_BI0 FOR SOZVEZDIE_ACTION_MOVE
ACTIVE BEFORE INSERT OR UPDATE POSITION 1
AS
begin
    new.xml='<distribution>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
    new.xml=new.xml||'<map_pharmacy_id>'||new.map_pharmacy_id||'</map_pharmacy_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<distribution_id>'||new.distribution_id||'</distribution_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<batch_id>'||new.batch_id||'</batch_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<doc_date>'||new.doc_date||'</doc_date>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<doc_type>'||new.doc_type||'</doc_type>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<doc_number>'||new.doc_number||'</doc_number>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<pos_number>'||new.pos_number||'</pos_number>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<check_number>'||new.check_number||'</check_number>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<check_unique_number>'||new.check_unique_number||'</check_unique_number>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
    new.xml=new.xml||'<quantity>'||new.quantity||'</quantity>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<purchase_sum_nds>'||new.purchase_sum_nds||'</purchase_sum_nds>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<retail_sum_nds>'||new.retail_sum_nds||'</retail_sum_nds>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<discount_sum>'||new.discount_sum||'</discount_sum>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<cashier_id>'||new.cashier_id||'</cashier_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<cashier_full_name>'||new.cashier_full_name||'</cashier_full_name>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<cashier_tin>'||new.cashier_tin||'</cashier_tin>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<resale_sign>'||new.resale_sign||'</resale_sign>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'</distribution>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;

end
^


/* Trigger: SOZVEZDIE_ACTION_MOVE_BI1 */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_MOVE_BI1 FOR SOZVEZDIE_ACTION_MOVE
ACTIVE BEFORE INSERT POSITION 0
AS

begin

 new.doc_number=replace(new.doc_number,'&','&amp;');
 new.doc_number=replace(new.doc_number,'<','&lt;');
 new.doc_number=replace(new.doc_number,'>','&gt;');
 new.doc_number=replace(new.doc_number,'''','&apos;');
 new.doc_number=replace(new.doc_number,'"','&quot;');

 new.cashier_full_name=replace(new.cashier_full_name,'&','&amp;');
 new.cashier_full_name=replace(new.cashier_full_name,'<','&lt;');
 new.cashier_full_name=replace(new.cashier_full_name,'>','&gt;');
 new.cashier_full_name=replace(new.cashier_full_name,'''','&apos;');
 new.cashier_full_name=replace(new.cashier_full_name,'"','&quot;');



end
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
/******************************************************************************/
/***               Generated by IBExpert 05.04.2019 15:23:46                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_SOZVEZDIE_ACTION_REMHANT_ID;

CREATE TABLE SOZVEZDIE_ACTION_REMHANT (
    ID                               DM_ID /* DM_ID = BIGINT */,
    MAP_PHARMACY_ID                  DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    BATCH_ID                         DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    DATES                            DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    OPENING_BALANCE                  DM_DOUBLE /* DM_DOUBLE = DOUBLE PRECISION */,
    CLOSING_BALANCE                  DM_DOUBLE /* DM_DOUBLE = DOUBLE PRECISION */,
    INPUT_RETAIL_PRICE_BALANCE       NUMERIC(15,2),
    INPUT_PURCHASING_PRICE_BALANCE   NUMERIC(15,2),
    OUTPUT_RETAIL_PRICE_BALANCE      NUMERIC(15,2),
    OUTPUT_PURCHASING_PRICE_BALANCE  NUMERIC(15,2),
    PRICE                            DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    PRICE_O                          DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    XML                              DM_TEXT_BIG /* DM_TEXT_BIG = VARCHAR(10000) */
);




/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: SOZVEZDIE_ACTION_REMHANT_BI */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_REMHANT_BI FOR SOZVEZDIE_ACTION_REMHANT
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_SOZVEZDIE_ACTION_REMHANT_id,1);
end
^


/* Trigger: SOZVEZDIE_ACTION_REMHANT_BIU0 */
CREATE OR ALTER TRIGGER SOZVEZDIE_ACTION_REMHANT_BIU0 FOR SOZVEZDIE_ACTION_REMHANT
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
begin
  new.xml='<remhant>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
   new.xml=new.xml||'<map_pharmacy_id>'||new.map_pharmacy_id||'</map_pharmacy_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<batch_id>'||new.batch_id||'</batch_id>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<date>'||new.dates||'</date>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<opening_balance>'||round(new.opening_balance,6)||'</opening_balance>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<closing_balance>'||round(new.closing_balance,6)||'</closing_balance>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<input_retail_price_balance>'||new.input_retail_price_balance||'</input_retail_price_balance>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<input_purchasing_price_balance>'||new.input_purchasing_price_balance||'</input_purchasing_price_balance>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<output_retail_price_balance>'||new.output_retail_price_balance||'</output_retail_price_balance>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'<output_purchasing_price_balance>'||new.output_purchasing_price_balance||'</output_purchasing_price_balance>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;
  new.xml=new.xml||'</remhant>'||ASCII_CHAR(13)||ASCII_CHAR(10) ;

end
^


SET TERM ; ^




SET TERM ^ ;

create or alter procedure PR_SOZVEZDIE_BATCH (
    DATE_BEG DM_DATETIME,
    DATE_END DM_DATETIME,
    IFFIRST DM_ID)
as
begin


if (:iffirst=1) then
    begin
    INSERT into sozvezdie_action_batch (map_batch_id,real_quant_beg)
         select
            dd.part_id,
            abs(sum(dd.quant))
        from
            docs d
       join doc_detail dd on dd.doc_id=d.id
        where
            d.commitdate <=:date_end
            and dd.part_id is not null

        group by
            dd.part_id
        having (abs(sum(dd.quant))>0.001) or
         ((select count(dd1.id) from doc_detail dd1 left join docs on docs.id=dd1.doc_id where dd1.part_id=dd.part_id and docs.commitdate between :date_beg and :date_end)>0);

     --suspend;
    end

else
    begin
         INSERT into sozvezdie_action_batch (map_batch_id)
        select
            dd.part_id
        from
            docs d
         join doc_detail dd on dd.doc_id=d.id
        where
            d.commitdate between :date_beg and :date_end
            and dd.part_id is not null
          --  and d.doc_type in (1,11,10,17,2,3,4,5,6,9,20)
        group by
            dd.part_id;
      --   having abs(sum(dd.quant))>0.001
--        into :part_id
--         do
    --  suspend;
    end
 suspend;
end^

SET TERM ; ^


SET TERM ^ ;

create or alter procedure PR_SOZVEZDIE_FORMAT_DATETIME (
    FORMATING_DATE DM_DATETIME,
    ONLYDATA DM_ID_NULL)
returns (
    RESULT DM_TEXT)
as
declare variable DAYS DM_TEXT;
declare variable MONTHS DM_TEXT;
declare variable YEARS DM_TEXT;
declare variable HOURS DM_TEXT;
declare variable MINUTES DM_TEXT;
declare variable SECONDS DM_TEXT;
begin
  if (:formating_date is null) then
  result=null;
  else
  begin
  days= extract(day from :formating_date);
  months= extract(month from :formating_date);
  years= extract(year from :formating_date);
  hours= extract(hour from :formating_date);
  minutes= extract(minute from :formating_date);
  seconds=round(extract(second from :formating_date));
  if (seconds=60) then seconds=59;
  if (:ONLYDATA is not null) then
    begin
    hours=0;minutes=0;seconds=0;
    end
  if (char_length(months)=1) then months='0'||months;
  if (char_length(days)=1) then days='0'||days;
  if (char_length(hours)=1) then hours='0'||hours;
  if (char_length(minutes)=1) then minutes='0'||minutes;
  if (char_length(seconds)=1) then seconds='0'||seconds;


  result = years||'-'||months||'-'||days||'T'||hours||':'||minutes||':'||seconds;
  end
  suspend;
end^

SET TERM ; ^
SET TERM ^ ;

create or alter procedure PR_GET_WAREBASE_FROM_DATE (
    DATE_W DM_DATETIME,
    PARTID DM_ID)
returns (
    QUANT DM_DOUBLE)
as
begin
  --for
  Select
     -- dd.part_id,
     cast(coalesce(sum(dd.quant),0)as numeric (9,2))
  from
   doc_detail dd
  left join docs d on d.id=dd.doc_id
  where 
    d.commitdate <= :DATE_W and
    dd.part_id =:partid
--  group by dd.part_id
 -- having abs(sum(dd.quant))>0.001
  into :quant;
--  do
  suspend;
end^

SET TERM ; ^
/******************************************************************************/
SET TERM ^ ;

create or alter procedure PR_SOZVEZDIE_ACTION_BATCH (
    DEPARTMENT_CODE DM_ID,
    DATE_START DM_DATETIME,
    DATE_END DM_DATETIME,
    IFFIRST DM_ID)
returns (
    MAP_BATCH_ID DM_TEXT,
    MAP_PHARMACY_ID DM_TEXT,
    MAP_PHARMACY_NAME DM_TEXT,
    NOMENCLATURE_ID DM_TEXT,
    MAP_NOMENCLATURE_NAME DM_TEXT,
    MAP_PRODUCT_CODE DM_TEXT,
    MAP_PRODUCT_NAME DM_TEXT,
    PRODUCER_ID DM_TEXT,
    MAP_PRODUCER_CODE DM_TEXT,
    MAP_PRODUCER_NAME DM_TEXT,
    PRODUCER_COUNTRY_ID DM_TEXT,
    MAP_PRODUCER_COUNTRY_CODE DM_TEXT,
    MAP_PRODUCER_COUNTRY_NAME DM_TEXT,
    MAP_SUPPLIER_CODE DM_TEXT,
    MAP_SUPPLIER_TIN DM_TEXT,
    SUPPLIER_NAME DM_TEXT,
    BATCH_DOC_DATE DM_TEXT,
    BATCH_DOC_NUMBER DM_TEXT,
    PURCHASE_PRICE_NDS DM_TEXT,
    PURCHASE_NDS DM_TEXT,
    RETAIL_PRICE_NDS DM_TEXT,
    RETAIL_NDS DM_TEXT,
    BARCODE DM_TEXT,
    SIGN_COMISSION DM_TEXT,
    NOMENCLATURE_CODES DM_TEXT)
as
begin
if (:iffirst=0) then
     begin
     delete from sozvezdie_action_batch where sozvezdie_action_batch.real_quant_beg is null;
     execute procedure pr_sozvezdie_batch (:date_start,:date_end,:iffirst);
     delete from sozvezdie_action_batch1 where sozvezdie_action_batch1.real_quant_beg is null;
     insert into sozvezdie_action_batch1 (map_batch_id,
               map_pharmacy_id,
               map_pharmacy_name,
               nomenclature_id,
               map_nomenclature_name,
               map_product_code,
               map_product_name,
               producer_id,
               map_producer_code,
               map_producer_name,
               producer_country_id,
               map_producer_country_code,
               map_producer_country_name,
               map_supplier_code,
               map_supplier_tin,
               supplier_name,
               batch_doc_date,
               batch_doc_number,
               purchase_price_nds,
               purchase_nds,
               retail_price_nds,
               retail_nds,
               barcode,
               sign_comission,
               nomenclature_codes)
           select distinct
            p.map_batch_id as map_batch_id,
            :department_code as map_pharmacy_id,
            (select p.param_value  from params p where p.param_id='ORG_NAME_SHORT')as map_pharmacy_name,
            '' as nomenclature_id,
            vname.svalue as map_nomenclature_name,
            '' as map_product_code,
            '' as map_product_name,
            '' as producer_id,
            w.orig_izg_id as map_producer_code,
            vorig_izg.svalue as map_producer_name,
            '' as producer_country_id,
            w.country_id as map_producer_country_code,
            vcountry.svalue as map_producer_country_name,
            d.agent_id as map_supplier_code,
            a.inn as map_supplier_tin,
            a.caption as supplier_name,
            (select RESULT from pr_sozvezdie_format_datetime(d.commitdate,0)) as batch_doc_date,
            d.docnum as batch_doc_number,
            cast (p1.price_o as numeric(10,2)) as purchase_price_nds,
            cast((select deps.ndsr from deps where deps.id = p1.dep)as numeric (3,0)) as purchase_nds,
            cast (p1.price as numeric(10,2)) as retail_price_nds,
            cast (p1.nds as numeric(9,0)) as retail_nds,
            w.barcode as barcode,
            '0' as sign_comission,
            w.name_id as nomenclature_codes
         from  SOZVEZDIE_ACTION_BATCH  p
         join parts p1 on p1.id=p.map_batch_id
        -- left join doc_detail dd on dd.part_id=p.part_id
          join docs d on d.id = p1.doc_id --and d.doc_type in (1,2,20)
          join agents a on a.id=d.agent_id
         join WARES w on p1.ware_id=w.id
         join vals vname on w.name_id=vname.id
         join vals vorig_izg on w.orig_izg_id=vorig_izg.id
         join vals vcountry on w.country_id=vcountry.id;
        --where
        --  exists(select docs.docdate from docs left join doc_detail dd on dd.part_id=p.map_batch_id where docs.docdate  between :date_start and :date_en


      suspend;
     end
else
begin
     delete from sozvezdie_action_batch where sozvezdie_action_batch.real_quant_beg is not null;
     execute procedure pr_sozvezdie_batch (:date_start,:date_end,:iffirst);
     delete from sozvezdie_action_batch1 where sozvezdie_action_batch1.real_quant_beg is not null;
     insert into sozvezdie_action_batch1 (map_batch_id,
               map_pharmacy_id,
               map_pharmacy_name,
               nomenclature_id,
               map_nomenclature_name,
               map_product_code,
               map_product_name,
               producer_id,
               map_producer_code,
               map_producer_name,
               producer_country_id,
               map_producer_country_code,
               map_producer_country_name,
               map_supplier_code,
               map_supplier_tin,
               supplier_name,
               batch_doc_date,
               batch_doc_number,
               purchase_price_nds,
               purchase_nds,
               retail_price_nds,
               retail_nds,
               barcode,
               sign_comission,
               nomenclature_codes)
      select
            p.map_batch_id as map_batch_id,
            :department_code as map_pharmacy_id,
            (select p.param_value  from params p where p.param_id='ORG_NAME_SHORT')as map_pharmacy_name,
            '' as nomenclature_id,
            vname.svalue as map_nomenclature_name,
            '' as map_product_code,
            '' as map_product_name,
            '' as producer_id,
            w.orig_izg_id as map_producer_code,
            vorig_izg.svalue as map_producer_name,
            '' as producer_country_id,
            w.country_id as map_producer_country_code,
            vcountry.svalue as map_producer_country_name,
            d.agent_id as map_supplier_code,
            a.inn as map_supplier_tin,
            a.caption as supplier_name,
            (select RESULT from pr_sozvezdie_format_datetime(d.commitdate,0)) as batch_doc_date,
            d.docnum as batch_doc_number,
            cast (p1.price_o as numeric(10,2)) as purchase_price_nds,
            cast((select deps.ndsr from deps where deps.id = p1.dep)as numeric (3,0)) as purchase_nds,
            cast (p1.price as numeric(10,2)) as retail_price_nds,
            cast (p1.nds as numeric(9,0)) as retail_nds,
            w.barcode as barcode,
            '0' as sign_comission,
            w.name_id as nomenclature_codes
         from SOZVEZDIE_ACTION_BATCH  p

         left join parts p1 on p1.id=p.map_batch_id
         left join docs d on d.id = p1.doc_id --and d.doc_type in (1,2,20)
         inner join agents a on a.id=d.agent_id
         join WARES w on p1.ware_id=w.id
         inner join vals vname on w.name_id=vname.id
         inner join vals vorig_izg on w.orig_izg_id=vorig_izg.id
         inner join vals vcountry on w.country_id=vcountry.id;

--         where
--           d.docdate between :date_start||':00:00:00' and :date_end||':23:59:59'

      suspend;
     end
end^

SET TERM ; ^

SET TERM ^ ;

create or alter procedure PR_SOZVEZDIE_ACTION_MOVE (
    DEPARTMENTCODE DM_TEXT,
    DATE_START DM_DATETIME,
    DATE_END DM_DATETIME,
    DATE_STOP DM_DATETIME,
    IFFIRST DM_ID)
returns (
    MAP_PHARMACY_ID DM_TEXT,
    DISTRIBUTION_ID DM_TEXT,
    BATCH_ID DM_TEXT,
    DOC_DATE DM_TEXT,
    DOC_TYPE DM_TEXT,
    DOC_NUMBER DM_TEXT,
    POS_NUMBER DM_TEXT,
    CHECK_NUMBER DM_TEXT,
    CHECK_UNIQUE_NUMBER DM_TEXT,
    QUANTITY DM_TEXT,
    PURCHASE_SUM_NDS DM_TEXT,
    RETAIL_SUM_NDS DM_TEXT,
    DISCOUNT_SUM DM_TEXT,
    CASHIER_ID DM_TEXT,
    CASHIER_FULL_NAME DM_TEXT,
    CASHIER_TIN DM_TEXT,
    RESALE_SIGN DM_TEXT)
as
begin
if (:iffirst=0) then
    begin
    DELETE from sozvezdie_action_move where firsttime is null;
    INSERT INTO sozvezdie_action_move (map_pharmacy_id,
            distribution_id,
            batch_id,
            doc_date,
            doc_type,
            doc_number,
            pos_number,
            check_number,
            check_unique_number,
            quantity,
            purchase_sum_nds,
            retail_sum_nds,
            discount_sum,
            cashier_id,
            cashier_full_name,
            cashier_tin,
            resale_sign)
      select
      :departmentcode as map_pharmacy_id,
               d.id||dd.part_id as distribution_id,
               dd.part_id as batch_id,
               (select RESULT from pr_sozvezdie_format_datetime(d.commitdate,null)) as  doc_date,
               case d.doc_type
                when 1 then 3
                when 2 then 6
                when 3 then 2
                when 4 then 5
                when 5 then 8
                when 6 then 7
                when 17 then 8
                when 10 then 8
                when 9 then 4
                when 11 then 1
                when 20 then 9
                when 8 then iif (dd.quant>0,9,8)
                when 7 then iif (dd.quant>0,9,8)
               end as doc_type,
    
               iif(d.doc_type=3,(select d1.docnum from docs d1 where cast(d1.docdate as date)=d.datez and d1.vshift=d.vshift and d1.doc_type=13),
                left(d.docnum,iif(position(' ',d.docnum)=0,char_length(d.docnum), position(' ',d.docnum))))as doc_number,
               iif(d.doc_type=3,d.device_num,'')as pos_number,
               iif(d.doc_type=3,d.docnum,'')as check_number,
               iif(d.doc_type=3,d.docnum,'')as check_unique_number,
               cast(abs(dd.quant)as numeric(10,6)) as quantity,
             cast(abs(dd.summa_o)as numeric(10,2)) as purchase_sum_nds,
             cast(abs(dd.summa)+abs(dd.sum_dsc) as numeric(10,2)) as retail_sum_nds,
             cast(abs(dd.sum_dsc) as numeric(9,2)) as discount_sum,
             u.d$uuid as cashier_id,
             u.username as cashier_full_name,
             coalesce(u.inn,'') as cashier_tin,
             '0' as resale_sign
                from sozvezdie_action_batch p1

       join doc_detail dd on dd.part_id=p1.map_batch_id
    
      inner join docs d on d.id = dd.doc_id  and d.doc_type in (1,11,10,17,2,3,4,5,6,9,8,20,7) and d.commitdate between :date_start and :date_end
    
     -- left join parts p on dd.part_id=p1.part_id
      join users u on u.id=d.owner
      where  --d.commitdate between :date_start and :date_end
      --and
      p1.real_quant_beg is null
       order by d.commitdate ;

      suspend;
    end
else
   begin
      DELETE from sozvezdie_action_move where firsttime is not null;
    INSERT INTO sozvezdie_action_move (map_pharmacy_id,
            distribution_id,
            batch_id,
            doc_date,
            doc_type,
            doc_number,
            pos_number,
            check_number,
            check_unique_number,
            quantity,
            purchase_sum_nds,
            retail_sum_nds,
            discount_sum,
            cashier_id,
            cashier_full_name,
            cashier_tin,
            resale_sign,
            firsttime)
      select
              :departmentcode as map_pharmacy_id,
               p.map_batch_id as distribution_id,
               p.map_batch_id as batch_id,
               (select RESULT from pr_sozvezdie_format_datetime(:date_start,null)) as  doc_date,
               '9' as doc_type,
               'ÐŸÐµÑ€Ð²Ð¸Ñ‡Ð½Ð°Ñ Ð²Ñ‹Ð³Ñ€ÑƒÐ·ÐºÐ°'as doc_number,
               ''as pos_number,
               ''as check_number,
               ''as check_unique_number,
               cast(abs(p.real_quant_beg)as numeric(10,6)) as quantity,
             cast(abs(p1.price_o*p.real_quant_beg)as numeric(10,2)) as purchase_sum_nds,
             cast(abs(p1.price*p.real_quant_beg) as numeric(10,2)) as retail_sum_nds,
             cast(0 as numeric(9,2)) as discount_sum,
             '' as cashier_id,
             '' as cashier_full_name,
             '' as cashier_tin,
             '0' as resale_sign,
             '1' as firsttime
                from sozvezdie_action_batch p
    
     -- left join doc_detail dd on dd.part_id=p.part_id
     -- inner join docs d on d.id = dd.doc_id --and d.doc_type in (1,11,10,17,2,3,4,5,6,9,20)
      left join parts p1 on p1.id=p.map_batch_id
      --left join users u on u.id=d.owner
     -- where  d.docdate between :date_start and :date_stop order by d.docdate
     where p.real_quant_beg>0.001;

      suspend;
    end
end^

SET TERM ; ^


SET TERM ^ ;

create or alter procedure PR_SOZVEZDIE_ACTION_REMHANT (
    DEPARTMENTCODE DM_TEXT,
    DATE_START DM_DATETIME,
    DATE_END DM_DATETIME,
    IFFIRST DM_ID)
returns (
    MAP_PHARMACY_ID DM_TEXT,
    BATCH_ID DM_TEXT,
    DATES DM_TEXT,
    OPENING_BALANCE numeric(15,6),
    CLOSING_BALANCE numeric(15,6),
    INPUT_RETAIL_PRICE_BALANCE numeric(15,2),
    INPUT_PURCHASING_PRICE_BALANCE numeric(15,2),
    OUTPUT_RETAIL_PRICE_BALANCE numeric(15,2),
    OUTPUT_PURCHASING_PRICE_BALANCE numeric(15,2),
    PRICE numeric(15,2),
    PRICE_O numeric(15,2))
as
declare variable DOC_ID DM_ID;
declare variable DATESQL DM_DATETIME;
begin
if (:iffirst=0) then
    begin
    delete from sozvezdie_action_remhant where sozvezdie_action_remhant.batch_id is not null;
     --date_start=date_start;
     while (date_start<>current_date+1) do
     begin
      for select id from docs where docs.commitdate between :date_start and :date_end into :doc_id
      do
      begin
      insert into sozvezdie_action_remhant (map_pharmacy_id,
       batch_id,
       dates,
       opening_balance,
       closing_balance,
       input_retail_price_balance,
       input_purchasing_price_balance,
       output_retail_price_balance,
       output_purchasing_price_balance,
       price,
       price_o)
        select
                query.map_pharmacy_id,
                query.batch_id,
                query.dates,
                cast(query.opening_balance as dm_double)as opening_balance,
                cast(query.closing_balance as dm_double)as closing_balance,
                cast(query.opening_balance * query.price as dm_double)as input_retail_price_balance,
                cast(query.opening_balance * query.price_o as dm_double)as input_purchasing_price_balance,
                cast(query.closing_balance * query.price as dm_double)as output_retail_price_balance,
                cast(query.closing_balance * query.price_o as dm_double)as output_purchasing_price_balance,
                cast(query.price as dm_double),
                cast(query.price_o as dm_double)
            from
                (select
                    :departmentcode as map_pharmacy_id,
                    sab.map_batch_id as batch_id,
                    (select result from pr_sozvezdie_format_datetime(:date_start,0)) as dates,
    --(select cast(sum(dd1.quant) as numeric(9,4)) from doc_detail dd1 where dd1.doc_commitdate<=current_date-93 and dd1.part_id=dd.part_id)
                    (select quant from pr_get_warebase_from_date(:date_start,sab.map_batch_id))as opening_balance,
                    (select quant from pr_get_warebase_from_date(:date_end,sab.map_batch_id)) as closing_balance,
                   -- cast(sum(abs(dd.summa_o))as dm_double)as output_purchasing_price_balance,
                    cast(p.price as dm_double)as price,
                    cast(p.price_o as dm_double)as price_o
    
                  from sozvezdie_action_batch sab
    
                  join doc_detail dd on dd.doc_id =:doc_id and dd.part_id=sab.map_batch_id

                  join parts p on p.id=sab.map_batch_id
                -- inner join docs d on dd.doc_id=d.id
                  where
                    sab.real_quant_beg is null --and d.commitdate between :date_start and :date_end

                 group by dates,batch_id,price,price_o
                 )  query   ;

    end
     date_start=date_start+1;
     date_end=date_end+1;
     end


    suspend;
  end
else
    begin
     delete from sozvezdie_action_remhant where sozvezdie_action_remhant.batch_id is null;
      for select id from docs where docs.commitdate between :date_start and :date_end into :doc_id
      do
      begin
      insert into sozvezdie_action_remhant (map_pharmacy_id,
       batch_id,
       dates,
       opening_balance,
       closing_balance,
       input_retail_price_balance,
       input_purchasing_price_balance,
       output_retail_price_balance,
       output_purchasing_price_balance,
       price,
       price_o)
    
         select
                query.map_pharmacy_id,
                query.batch_id,
                query.dates,
                cast(0 as numeric(9,6))as opening_balance,
                cast(query.closing_balance as numeric(9,6))as closing_balance,
                cast(0 as numeric(9,2))as input_retail_price_balance,
                cast(0  as numeric(9,2))as input_purchasing_price_balance,
                cast(query.closing_balance * query.price as numeric(9,2))as output_retail_price_balance,
                cast(query.closing_balance * query.price_o as numeric(9,2))as output_purchasing_price_balance,
                cast(query.price as numeric(9,2)),
                cast(query.price_o as numeric(9,2))
            from
                (select
                    :departmentcode as map_pharmacy_id,
                    dd.part_id as batch_id,
                    (select result from pr_sozvezdie_format_datetime(:date_start,0)) as dates,
    --(select cast(sum(dd1.quant) as numeric(9,4)) from doc_detail dd1 where dd1.doc_commitdate<=current_date-93 and dd1.part_id=dd.part_id)
                    (select quant from pr_get_warebase_from_date(:date_start,dd.part_id))as opening_balance,
                   iif(p1.real_quant_beg =(select quant from pr_get_warebase_from_date(:date_end,dd.part_id)),(select quant from pr_get_warebase_from_date(:date_end,dd.part_id)),p1.real_quant_beg-(select quant from pr_get_warebase_from_date(:date_end,dd.part_id))) as closing_balance,
                    --cast(sum(abs(dd.summa_o))as numeric(9,2))as output_purchasing_price_balance,
                    cast(p.price as numeric(9,2))as price,
                    cast(p.price_o as numeric(9,2))as price_o

    
                           from sozvezdie_action_batch p1
    
                  join doc_detail dd on dd.doc_id =:doc_id and dd.part_id=p1.map_batch_id

                  join parts p on p.id=p1.map_batch_id
                -- inner join docs d on dd.doc_id=d.id
                  where
                    p1.real_quant_beg is not null --and d.commitdate between :date_start and :date_end

                 group by dates,batch_id,price,price_o,p1.real_quant_beg
                 )  query   ;



        end
     suspend;
end
end^

SET TERM ; ^

SET BLOBFILE 'e:\TMS\Manager\exp_to_sozvezdie\TMS_SOZVEZDIE.hex';
INSERT INTO GROUPS (ID, PARENT_ID, CAPTION, GROUPTABLE, STATUS, INSERTDT, SYSTEMFLAG, DESCRIPTION, IMAGEINDEX, DATA, COLOR, SORTING, BASE_AGENT_ID, SID) VALUES (19999, 61, 'Âûãðóçêà â ñîçâåçäèå', 'TMS', 0, '30-MAR-2019 16:54:30', 0, NULL, -1,:h00000000_7FFFFFFF, NULL, NULL, 0, NULL);



commit;







