/******************************************************************************/
/***               Generated by IBExpert 21.08.2019 10:56:29                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE MFO_WAREBASE (
    PROFILE_ID    DM_ID /* DM_ID = BIGINT NOT NULL */,
    SPROFILE      DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    SNAME         DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    BCODE_IZG     DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    QUANT         DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    INN           DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    GODENDO_DATE  DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    SIZG          DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    SCOUNTRY      DM_TEXT /* DM_TEXT = VARCHAR(250) */,
    WARE_ID       DM_UUID_NULL /* DM_UUID_NULL = CHAR(36) */
);




/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX MFO_WAREBASE_IDX1 ON MFO_WAREBASE (WARE_ID, PROFILE_ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: MFO_WAREBASE_BI0 */
CREATE OR ALTER TRIGGER MFO_WAREBASE_BI0 FOR MFO_WAREBASE
ACTIVE BEFORE INSERT POSITION 0
AS
begin
 new.sname = (select sname from wares w where w.id=new.ware_id );
 new.bcode_izg=(select w.barcode from wares w where w.id=new.ware_id );
 new.sizg=(select svalue from vals v JOIN wares w on w.id=new.ware_id where v.id=w.izg_id);
 new.scountry=(select svalue from vals v JOIN wares w on w.id=new.ware_id where v.id=w.country_id);
 new.sprofile=(select caption from g$profiles g where g.id=new.profile_id);
 new.inn = (select first 1 p1.param_value as inn from params p1 where p1.param_id ='ORG_INN' and p1.g$profile_id=new.profile_id);

end
^

SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
